- id: '1666907927444'
  alias: Automatically turn off Aerating Appartment
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.aerating_appartment
    to: 'on'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - service: homeassistant.turn_off
    data: {}
    target:
      entity_id: input_boolean.aerating_appartment
  mode: restart
- id: '1676864639936'
  alias: Clean the entrance
  description: Send Vacuum to the entrance
  trigger:
  - platform: webhook
    webhook_id: vacuum-entrance
  condition: []
  action:
  - data:
      command: app_zoned_clean
      params:
      - - 20328
        - 25979
        - 23164
        - 27118
        - 1
    service: vacuum.send_command
    target:
      entity_id: vacuum.xiaomi_vacuum_cleaner
  mode: single
- id: '1676864830167'
  alias: Clean The Entrance
  description: Send Vacuum to the entrance
  trigger:
  - platform: webhook
    webhook_id: vacuum-entrance
    allowed_methods:
    - POST
    - PUT
    local_only: true
  condition: []
  action:
  - data:
      command: app_zoned_clean
      params:
      - - 20328
        - 25979
        - 23164
        - 27118
        - 1
    entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.send_command
  mode: single
- id: '1683153489151'
  alias: Clean The Kitchen
  description: Send the vacuum to the Kitchen
  trigger:
  - platform: webhook
    webhook_id: vacuum-kitchen
    allowed_methods:
    - POST
    - PUT
    local_only: true
  condition: []
  action:
  - data:
      command: app_zoned_clean
      params:
      - - 31042
        - 24956
        - 37523
        - 25886
        - 1
      - - 30932
        - 24815
        - 32741
        - 26061
        - 1
      - - 32442
        - 25833
        - 35761
        - 28903
        - 1
    entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.send_command
  mode: single
- id: '1683153520952'
  alias: Clean The Kitchen
  description: Send the vacuum to the Kitchen
  trigger:
  - platform: webhook
    webhook_id: vacuum-kitchen
    allowed_methods:
    - POST
    - PUT
    local_only: true
  condition: []
  action:
  - data:
      command: app_zoned_clean
      params:
      - - 31042
        - 24956
        - 37523
        - 25886
        - 1
      - - 30932
        - 24815
        - 32741
        - 26061
        - 1
      - - 32442
        - 25833
        - 35761
        - 28903
        - 1
    entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.send_command
  mode: single
- id: '1683153680525'
  alias: Clean The Kitchen
  description: Send the vacuum to the Kitchen
  trigger:
  - platform: webhook
    webhook_id: vacuum-kitchen
    allowed_methods:
    - POST
    - PUT
    local_only: true
  condition: []
  action:
  - data:
      command: app_zoned_clean
      params:
      - - 31042
        - 24956
        - 37523
        - 25886
        - 1
      - - 30932
        - 24815
        - 32741
        - 26061
        - 1
      - - 32442
        - 25833
        - 35761
        - 28903
        - 1
    entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.send_command
  mode: single
- id: '1683153758859'
  alias: Clean The Dungeon
  description: Send vacuum to the dungeon
  trigger:
  - platform: webhook
    webhook_id: vacuum-dungeon
    allowed_methods:
    - POST
    - PUT
    local_only: true
  condition: []
  action:
  - data:
      command: app_zoned_clean
      params:
      - - 22832
        - 27114
        - 26009
        - 31394
        - 1
    entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.send_command
  mode: single
- id: '1683153776810'
  alias: Clean the bedroom
  description: Send Vacuum to bedroom
  trigger:
  - platform: webhook
    webhook_id: vacuum-bedroom
    allowed_methods:
    - POST
    - PUT
    local_only: true
  condition: []
  action:
  - data:
      command: app_zoned_clean
      params:
      - - 18821
        - 27079
        - 23005
        - 31394
        - 1
    entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.send_command
  mode: single
- id: '1683153834126'
  alias: Clean the bedroom
  description: Send Vacuum to bedroom
  trigger:
  - platform: webhook
    webhook_id: vacuum-bedroom
    allowed_methods:
    - POST
    - PUT
    local_only: true
  condition: []
  action:
  - data:
      command: app_zoned_clean
      params:
      - - 18821
        - 27079
        - 23005
        - 31394
        - 1
    entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.send_command
  mode: single
- id: '1683153860372'
  alias: Clean the Living Room
  description: Send Vacuum to the living room
  trigger:
  - platform: webhook
    webhook_id: vacuum-livingroom
    allowed_methods:
    - POST
    - PUT
    local_only: true
  condition: []
  action:
  - data:
      command: app_zoned_clean
      params:
      - - 25915
        - 24728
        - 30979
        - 28517
        - 1
    entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.send_command
  mode: single
- id: '1683153892029'
  alias: Clean the hotbox
  description: Send vacuum to the hotbox
  trigger:
  - platform: webhook
    webhook_id: vacuum-hotbox
    allowed_methods:
    - POST
    - PUT
    local_only: true
  condition: []
  action:
  - data:
      command: app_zoned_clean
      params:
      - - 35840
        - 26763
        - 39473
        - 28833
        - 1
      - - 35792
        - 25833
        - 37585
        - 27289
        - 1
    entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.send_command
  mode: single
- id: '1683153916131'
  alias: Clean the Hallway
  description: Send robovac to the hallway
  trigger:
  - platform: webhook
    webhook_id: vacuum-hallway
    allowed_methods:
    - POST
    - PUT
    local_only: true
  condition: []
  action:
  - data:
      command: app_zoned_clean
      params:
      - - 19796
        - 24833
        - 25978
        - 27236
        - 1
    entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.send_command
  mode: single
- id: '1683153973666'
  alias: Clean the Bathroom
  description: Send Vacuum to the bathroom
  trigger:
  - platform: webhook
    webhook_id: vacuum-bathroom
    allowed_methods:
    - POST
    - PUT
    local_only: true
  condition: []
  action:
  - data:
      command: app_zoned_clean
      params:
      - - 30932
        - 26079
        - 32552
        - 29693
        - 1
    entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.send_command
  mode: single
- id: '1691007313405'
  alias: Assist Play Media
  description: ''
  trigger:
  - platform: conversation
    command:
    - play {artist}
  condition: []
  action:
  - service: media_player.play_media
    data:
      media_content_type: artist
      media_content_id: 'plex://{ "artist_name": "{{ trigger.slots.artist | replace(".","")
        }}", "shuffle": 1 ,"library_name": "Music", "allow_multiple": 1 }'
    target:
      entity_id: media_player.group_home_speakers
  mode: single
- id: '1691088980213'
  alias: Assist Play Playlist
  description: ''
  trigger:
  - platform: conversation
    command:
    - (start|play) [the] {playlist} playlist
  condition: []
  action:
  - service: media_player.play_media
    data:
      media_content_type: playlist
      media_content_id: 'plex://{ "playlist_name": "{{ trigger.slots.playlist | replace(".","")
        }}", "shuffle": 1 ,"library_name": "Music" }'
    target:
      entity_id: media_player.group_home_speakers
  mode: single
