- id: '1666907927444'
  alias: Automatically turn off Aerating Appartment
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.aerating_appartment
    to: 'on'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - service: homeassistant.turn_off
    data: {}
    target:
      entity_id: input_boolean.aerating_appartment
  mode: restart
- id: '1669312487522'
  alias: Start Panic at the disco Radio
  description: ''
  trigger:
  - platform: event
    event_type: ''
  condition: []
  action:
  - service: media_player.play_media
    data:
      media_content_id: PL6H6TfFpYvpersEdHECeWkocaPueTqieF
      media_content_type: playlist
      enqueue: play
    target:
      entity_id: media_player.ytube_music_player
  - wait_for_trigger:
    - platform: state
      entity_id:
      - media_player.ytube_music_player
      to: playing
    continue_on_timeout: true
  - service: ytube_music_player.start_radio
    data:
      entity_id: media_player.ytube_music_player
  mode: single
- id: '1676864639936'
  alias: Clean the entrance
  description: Send Vacuum to the entrance
  trigger:
  - platform: webhook
    webhook_id: vacuum-entrance
  condition: []
  action:
  - data:
      command: app_zoned_clean
      params:
      - - 20328
        - 25979
        - 23164
        - 27118
        - 1
    service: vacuum.send_command
    target:
      entity_id: vacuum.xiaomi_vacuum_cleaner
  mode: single
- id: '1676864774546'
  alias: Clean The Entrance
  description: Send Vacuum to the entrance
  trigger:
  - platform: webhook
    webhook_id: vacuum-entrance
  condition: []
  action:
  - data:
      command: app_zoned_clean
      params:
      - - 20328
        - 25979
        - 23164
        - 27118
        - 1
    entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.send_command
  mode: single
- id: '1676864830167'
  alias: Clean The Entrance
  description: Send Vacuum to the entrance
  trigger:
  - platform: webhook
    webhook_id: vacuum-entrance
  condition: []
  action:
  - data:
      command: app_zoned_clean
      params:
      - - 20328
        - 25979
        - 23164
        - 27118
        - 1
    entity_id: vacuum.xiaomi_vacuum_cleaner
    service: vacuum.send_command
  mode: single
