- id: '1691007313405'
  alias: Assist Play Media
  description: ''
  trigger:
  - platform: conversation
    command:
    - play {artist}
  condition: []
  action:
  - service: media_player.play_media
    data:
      media_content_type: artist
      media_content_id: 'plex://{ "artist_name": "{{ trigger.slots.artist | replace(".","")
        }}", "shuffle": 1 ,"library_name": "Music", "allow_multiple": 1 }'
    target:
      entity_id: media_player.group_home_speakers
  mode: single
- id: '1691088980213'
  alias: Assist Play Playlist
  description: ''
  trigger:
  - platform: conversation
    command:
    - (start|play) [the] {playlist} playlist
  condition: []
  action:
  - service: media_player.play_media
    data:
      media_content_type: playlist
      media_content_id: 'plex://{ "playlist_name": "{{ trigger.slots.playlist | replace(".","")
        }}", "shuffle": 1 ,"library_name": "Music" }'
    target:
      entity_id: media_player.group_home_speakers
  mode: single
- id: '1691094215164'
  alias: 'Assist: Set Thermostats'
  description: ''
  trigger:
  - platform: conversation
    command:
    - (set|change) [the] {thermostat} (AC|thermostat) to {temperature}
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: '{{ trigger.slots.temperature }}'
    target:
      entity_id: climate.{{ trigger.slots.thermostat }}_ac
  mode: single
- id: '1693412216159'
  alias: Assist play specific song
  description: ''
  trigger:
  - platform: conversation
    command:
    - (start|play) [the] song {song}
  condition: []
  action:
  - service: media_player.play_media
    data:
      media_content_type: music
      media_content_id: 'plex://{ "track_name": "{{ trigger.slots.song | replace(".","")
        }}", "allow_multiple": 1 ,"library_name": "Music" }'
    target:
      entity_id: media_player.group_home_speakers
  mode: single
- id: '1698434157594'
  alias: Update Map Extractor camera
  description: ''
  use_blueprint:
    path: PiotrMachowski/update_map_extractor.yaml
    input:
      vacuum: vacuum.xiaomi_vacuum_cleaner
      camera: camera.xiaomi_cloud_map_extractor
      mode_to_handle: turn_off_when_docked
- id: '1708472009602'
  alias: Play Music when maxi awakes at home
  description: This Automation will start music on the home group when maxi awakes
  trigger:
  - platform: state
    entity_id:
    - sensor.is_maxi_asleep
    from: asleep
    to: awake
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition:
  - condition: state
    entity_id: person.maximiliano
    state: home
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.group_home_speakers
    data:
      media_content_type: playlist
      media_content_id: 'plex://{ "playlist_name": "Maxi Music", "shuffle": 1 }'
    metadata: {}
  mode: single
- id: '1708472370553'
  alias: Stop bedroom speaker when I awake
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.sleeper_in_bedroom
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 3
      seconds: 0
  condition: []
  action:
  - service: media_player.media_stop
    metadata: {}
    data: {}
    target:
      entity_id: media_player.bedroom_speaker
  mode: single
