
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

http:
  # For extra security set this to only accept connections on localhost if NGINX is on the same machine
  # Uncommenting this will mean that you can only reach Home Assistant using the proxy, not directly via IP from other clients.
  #server_host: 192.168.0.5
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
  trusted_proxies: 
     - 192.168.0.5
     - 192.168.0.1      
######################################################################
recorder:
  purge_keep_days: 400
  db_url: !secret db_url
######################################################################
frontend:    
  themes: !include_dir_merge_named themes
######################################################################
browser_mod:
######################################################################
# lifx:
  # light:
    # - server: 192.168.0.15
      # port: 56700
    # - broadcast: 192.168.20.8
    # - broadcast: 192.168.20.9
    # - broadcast: 192.168.20.11
######################################################################
logger:
  default: warning
  logs:
      homeassistant.components.vacuum: debug
  # filters:
    # homeassistant.components.websocket_api.http.connection: 
      # - "espresense"
      # - "speaker"
      # - "ELECTRIC"
      # - "motion"
      # - "switch"
      # - "unit_of_measurement"
      # - ".*LOCAL.*"
######################################################################
media_source:
######################################################################
#includes
mqtt: !include /config/includes/mqtt.yaml
scene: !include /config/includes/scenes.yaml
media_player: !include /config/includes/media_player.yaml
notify: !include /config/includes/notify.yaml
binary_sensor: !include /config/includes/binsensors.yaml
sensor: !include /config/includes/sensors.yaml
light: !include /config/includes/lights.yaml
group: !include /config/includes/groups.yaml
automation: !include /config/includes/automations.yaml
script: !include /config/includes/scripts.yaml
rest_command: !include /config/includes/rest_command.yaml
alarm_control_panel: !include /config/includes/alarms.yaml
switch: !include /config/includes/switch.yaml
climate: !include /config/includes/climate.yaml
google_assistant: !include /config/includes/google_assistant.yaml
camera: !include /config/includes/cameras.yaml
proxmoxve: !include /config/includes/proxmoxve.yaml
template: !include /config/includes/template.yaml
monitor_docker: !include /config/includes/monitor_docker.yaml
######################################################################
homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.249
######################################################################
lovelace_gen:

lovelace:
  mode: yaml
######################################################################
