esphome:
  name: esphome-load-cells
  friendly_name: esphome load cells

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key_voice_assistant

ota:
  - platform: esphome
    password: "0751231f319ca91623b615930953406a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


sensor:
  - platform: hx711
    name: "HX711 Value"
    dout_pin: GPIO17 
    clk_pin: GPIO3
    gain: 128
    update_interval: 3s
    