substitutions:
  name: home-assistant-voice-09e688
  friendly_name: Home Assistant Voice 09e688
packages:
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: +piRI2s8TEiX/2Z0T8JWoQBhPjHdr9cVCEwW+zH15oI=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
