calibration_source:
  camera: true
col_span: '2'
col_span_lg: '3'
col_span_xl: '4'
entity: vacuum.xiaomi_vacuum_cleaner
map_locked: false
map_source:
  camera: camera.xiaomi_cloud_map_extractor
position: top
row_span: '1'
row_span_lg: '1'
row_span_xl: '1'
two_finger_pan: true
type: custom:xiaomi-vacuum-map-card
vacuum_platform: default
