esphome:
  name: es
  friendly_name: es

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "RGbULcHbhMEpl2arb1PXmMsWm8IJoKvalHwy3G/MzEg="

ota:
  - platform: esphome
    password: "1b3b9c60cf520e8235ecee9fef0703ac"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Es Fallback Hotspot"
    password: "ZXERy5DIokU0"

captive_portal:
    