substitutions:
  name: esp32-s3-box-3-0505ec
  friendly_name: ESP32 S3 Box 3 Office
packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 9uvOzvdvbCsug1jPknLWRI5BsbrNonIxJU5rX+cOd1c=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
