esphome:
  name: esp32-s3-box-3-livingroom-window-assistant
  friendly_name: ESP32 S3 Box 3 Livingroom Window Assistant

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "YtiqfwqNeaNldvW/OrMS881AJxA4WtedTJcbS1Vk9kk="

ota:
  - platform: esphome
    password: "8bae9c7d0d94cc2353ab8dbb9ccec969"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-S3-Box-3-Livingroom-Window-Assistant"
    password: "TAWRv7jK2n0V"

captive_portal:
    