esphome:
  name: esp32-livingroom-windows-assistant
  friendly_name: esp32 Livingroom Windows Assistant

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Q+R5BZHx6CW5CVRqhxqGuNqVN3SWgd/pTZFju81IiAE="

ota:
  - platform: esphome
    password: "024db1e8aa673753c40163a8f688a055"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-Livingroom-Windows-Assistant"
    password: "vxk9CgQL9sxl"

captive_portal:
    