substitutions:
  name: esp32-s3-box-lite
  friendly_name: ESP32 S3 Box Lite
packages:
  esphome.voice-assistant: github://esphome/firmware/voice-assistant/esp32-s3-box-lite.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: vVALTEouVx2ao+OmHuIO/8EN4in50IL4w7S7ea1zamI=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
