substitutions:
  micro_wake_word_model: alexa
  name: esp32-office
  friendly_name: ESP32 Office
packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
    encryption: 
      key: !secret api_key_voice_assistant


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
