esphome:
  name: esp32-s3-box-3-bedroom-assistant
  friendly_name: ESP32 S3 Box 3 Bedroom Assistant

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "7GnkhDJQJ68f0s5Jc5xG2Z0J7T3X3zPdxAzXQ4BI12A="

ota:
  - platform: esphome
    password: "c2afb374cfe01e59c71053107a0a4dc1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32-S3-Box-3-Bedroom-Assistant"
    password: "5vPOKghApuYJ"

captive_portal:
    