substitutions:
  name: esp32-s3-box-e233f8
  friendly_name: ESP32 S3 Box e233f8
packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 0wzEi0rSq05rw2Mua7E8eo2qQfgH5jtPt3m/DQ556W8=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
