- platform: xiaomi_cloud_map_extractor
  host: 192.168.20.26
  token: !secret vacuum_xiaomi_token
  username: maxi1134@hotmail.ca
  password: !secret vacuum_xiaomi_password
  draw: ['all']
  attributes:
    - calibration_points
    - rooms
    - calibration_points
    - charger
    - cleaned_rooms
    - country
    - goto
    - goto_path
    - goto_predicted_path
    - image
    - is_empty
    - map_name
    - no_go_areas
    - no_mopping_areas
    - obstacles
    - ignored_obstacles
    - obstacles_with_photo
    - ignored_obstacles_with_photo
    - path
    - room_numbers
    - rooms
    - vacuum_position
    - vacuum_room
    - vacuum_room_name
    - walls
    - zones