- platform: xiaomi_cloud_map_extractor
  host: 192.168.20.26
  scan_interval: 30
  token: !secret vacuum_xiaomi_token
  username: maxi1134@hotmail.ca
  password: !secret vacuum_xiaomi_password
  draw: ['all']
  attributes:
    - calibration_points