- platform: switch
  name: "Hotbox_Down_lavaLamp"
  entity_id: switch.plug_hotbox_down_lavalamp
- platform: switch
  name: "Bedroom_lavaLamp"
  entity_id: switch.plug_bedroom_lavalamp
- platform: switch
  name: "Dungeon_Plasmaball"
  entity_id: switch.plug_bedroom_plasmaball