sensor:
  - name: front_persons
    state_topic: "frigate/entrance/person"
  - name: double_take_facecam
    state_topic: "double-take/cameras/facecam"
  - name: double_take__frontdoor_mqtt
    state_topic: "double-take/cameras/front_door"    
  - name: "double_take_reolink_mqtt"
    state_topic: "double-take/cameras/front_door"
    value_template: |-
      # {{value}}       
  - name: "wyzecam_double_take_mqtt"
    state_topic: "double-take/cameras/wyzecam"
    value_template: |-
      {{value}}   
  - name: geovision_persons
    state_topic: "frigate/geovision/person"
  - name: facecam_persons
    state_topic: "frigate/facecam/person"
switch:
  - name: "Bathroom Fan"
    command_topic: "cmnd/sonoff_bathroomfan/POWER"
    state_topic: "stat/sonoff_bathroomfan/POWER"
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "ON"
    payload_not_available: "OFF"
    retain: false