substitutions:
  name: esp32-s3-box-lvw-assistant
  friendly_name: ESP32 S3 Box 3 LVW Assistant
  micro_wake_word_model: alexa
packages:
  esphome.voice-assistant: github://esphome/wake-word-voice-assistants/esp32-s3-box-3/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret api_key_voice_assistant


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
