substitutions:
  name: esp32-s3-box-e233f8
  friendly_name: ESP32 S3 Box e233f8
packages:
  esphome.voice-assistant: github://esphome/firmware/voice-assistant/esp32-s3-box.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: vxVKApFiT0XNi1k62KBLLXv60wiYBynlSsdZXTrQ+DE=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
