substitutions:
  name: esp32-s3-box-office-0505ec
  friendly_name: ESP32 S3 Box Office 0505ec
packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: JJ054KchMfJKCzFy6Pt0oHt4hRHU6vsEaAmR3yYgCyQ=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
