substitutions:  
  micro_wake_word_model: alexa
  name: esp32-s3-box-3-04dc50
  friendly_name: ESP32 S3 Box 3 04dc50
packages:
  esphome.voice-assistant: github://esphome/firmware/wake-word-voice-assistant/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: qgxR1tm2Zq8eT1sUdB7ogtaEdWfVNe3bII1hk17cQtc=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
