esphome:
  name: esp8266-soundlevel-patio

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "FdytKqIM9QrviF5Kvp2858adHD3Er4GWkfy67/ngwrw="

ota:
  password: "3bfaf7052b25233f0b88e4a89cb45342"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266-Soundlevel-Patio"
    password: "5Cji1n9uXIa2"

captive_portal:
    
#sensor:
#   - platform: adc
#     pin: A0
#     name: "Sound level"
#     update_interval: ".6s"
     # see https://esphome.io/components/sensor/adc.html
#     id: adc_mic_reading
#   - platform: ct_clamp
#     sensor: adc_mic_reading
#     name: "Sound level from my BOB-12758"
#     sample_duration: 250ms
#     update_interval: 500ms    
binary_sensor:
  - platform: gpio
    pin: GPIO4
    name: "Sound level Binary"